// 事件系统 postMessage.js
export const TRIGGER_POSTMESSAGE_DEVENT = 'TRIGGER_POSTMESSAGE_DEVENT'

// 数据更新
export const UPDATE_DATA = 'UPDATE_DATA'

export const INIT_TABLE_DATA = 'INIT_TABLE_DATA'
export const UPDATE_TABLE_DATA = 'UPDATE_TABLE_DATA'
export const UPDATE_ALL_TABLE_DATA = 'UPDATE_ALL_TABLE_DATA'

// 弹窗
export const OPEN_DIALOG = 'OPEN_DIALOG'
export const CLOSE_DIALOG = 'CLOSE_DIALOG'

// 发票弹窗 invoiceDialog.js
// 打印
export const OPEN_INVOICE_PRINT_DIALOG = 'OPEN_INVOICE_PRINT_DIALOG'
export const CLOSE_INVOICE_PRINT_DIALOG = 'CLOSE_INVOICE_PRINT_DIALOG'
// 作废
export const OPEN_INVOICE_INVALID_DIALOG = 'OPEN_INVOICE_INVALID_DIALOG'
export const CLOSE_INVOICE_INVALID_DIALOG = 'CLOSE_INVOICE_INVALID_DIALOG'
// 快递
export const OPEN_INVOICE_EXPRESS_DIALOG = 'OPEN_INVOICE_EXPRESS_DIALOG'
export const CLOSE_INVOICE_EXPRESS_DIALOG = 'CLOSE_INVOICE_EXPRESS_DIALOG'

// 专票冲红列表弹窗
export const OPEN_INVOICE_FLUSH_DIALOG = 'OPEN_INVOICE_FLUSH_DIALOG'
export const CLOSE_INVOICE_FLUSH_DIALOG = 'CLOSE_INVOICE_FLUSH_DIALOG'
// 冲红
export const OPEN_INVOICE_SPECIALRED_DIALOG = 'OPEN_INVOICE_SPECIALRED_DIALOG'
export const CLOSE_INVOICE_SPECIALRED_DIALOG = 'CLOSE_INVOICE_SPECIALRED_DIALOG'

// 查看
export const OPEN_INVOICE_VIEW_DIALOG = 'OPEN_INVOICE_VIEW_DIALOG'
export const CLOSE_INVOICE_VIEW_DIALOG = 'CLOSE_INVOICE_VIEW_DIALOG'
// 领用
export const OPEN_INVOICE_RECEIVE_DIALOG = 'OPEN_INVOICE_RECEIVE_DIALOG'
export const CLOSE_INVOICE_RECEIVE_DIALOG = 'CLOSE_INVOICE_RECEIVE_DIALOG'

// 关联合同
export const OPEN_RELATIONSHIP_AGREEMENT_DIALOG =
  'OPEN_RELATIONSHIP_AGREEMENT_DIALOG'
export const CLOSE_RELATIONSHIP_AGREEMENT_DIALOG =
  'CLOSE_RELATIONSHIP_AGREEMENT_DIALOG'

// 编辑销售方信息
export const OPEN_INVOICE_BASE_SELLER_DIALOG = 'OPEN_INVOICE_BASE_SELLER_DIALOG'
export const CLOSE_INVOICE_BASE_SELLER_DIALOG =
  'CLOSE_INVOICE_BASE_SELLER_DIALOG'

// 调整客户
export const OPEN_INVOICE_JURISDICTION_DIALOG =
  'OPEN_INVOICE_JURISDICTION_DIALOG'
export const CLOSE_INVOICE_JURISDICTION_DIALOG =
  'CLOSE_INVOICE_JURISDICTION_DIALOG'
